apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gateway-service

  template:
    metadata:
      labels:
        app: gateway-service

    spec:
      imagePullSecrets:
      - name: ecr-secret
      
      containers:
      - name: gateway-service
        image: 944765969321.dkr.ecr.ap-south-2.amazonaws.com/gateway-service:latest

        ports:
        - containerPort: 3003

        env:
        - name: USER_SERVICE
          value: "http://user-service:3000"

        - name: PRODUCT_SERVICE
          value: "http://product-service:3001"

        - name: ORDER_SERVICE
          value: "http://order-service:3002"

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5